categories:
- Gene clustering
- Genome comparison
description: Panaroo builds a graphical representation of the pangenome while performing a number of cleaning steps.
long_description: |
   The Panaroo algorithm builds a graphical representation of the pangenome 
   where nodes are genes and edges connect nodes if two genes appear adjacent to one another on at least one contig.
   The algorithm then uses this initial graph structure to perform a number of cleaning steps 
   which correct for many of the problems encountered in genome annotation. 
   Panaroo accepts annotated assemblies in GFF3 format as output by the popular annotation pipeline Prokka. 
   Unlike similar pangenome software, Panaroo attempts to preserve the full global context of each gene in the graph.
   
   https://github.com/gtonkinhill/panaroo
name: panaroo
owner: Gerry Tonkin-Hill
remote_repository_url: https://github.com/gtonkinhill/panaroo.git
homepage_url: https://github.com/gtonkinhill/panaroo
type: unrestricted